### ISSUE TITLE
SDF calculation?

### ISSUE THREAD

**Issue by wangzheallen** [yz-cnsdqz/PSI-release#1]
Nice work!~

May I ask how do you convert the mesh (obj) file to SDF? any hint code on that?
and is the SDF file we get in world coordinate or camera coordinate?
What does the "max","min" value means in the scenes_sdf',scenename+'.json' means?

Thanks!

**Comment by yz-cnsdqz** [comment]
Thanks for your interests. Pls see answers below.

> Nice work!~
> 
> May I ask how do you convert the mesh (obj) file to SDF? any hint code on that?
SDF computation involves some manual work. Briefly, Poisson remeshing is applied to first. We are sorry that the code is not provided, due to agreements of some dependencies.

> and is the SDF file we get in world coordinate or camera coordinate?
SDF is in the world coordinate.
 
> What does the "max","min" value means in the scenes_sdf',scenename+'.json' means?
The SDF domain (not the co-domain) is normalized. 
> 
> Thanks!

**Comment by wangzheallen** [comment]
Thanks for the clarification.

Usually SDF is composed of two part:
points: an N ✕ 3 numpy array containing the sample points
sdf: a numpy array of size N with the corresponding SDF values
May I ask whether the json file with 
max,min,dim value.
corresponds to mesh to voxel (sample grid is dim value)? say we want to sample 256*256*256 grid, thus the dim here is 256?
And max, min is 3 dim, which defines min and max value along "points: an N ✕ 3 numpy array containing the sample points"?

May I ask did you do scale_to_unit_sphere before sampling point and calculate SDF?
[https://github.com/marian42/mesh_to_sdf/blob/master/mesh_to_sdf/utils.py#L4](url)
Thanks.

**Comment by yz-cnsdqz** [comment]
> Thanks for the clarification.
> 
> Usually SDF is composed of two part:
> points: an N ✕ 3 numpy array containing the sample points
> sdf: a numpy array of size N with the corresponding SDF values
> May I ask whether the json file with
> max,min,dim value.
> corresponds to mesh to voxel (sample grid is dim value)? say we want to sample 256_256_256 grid, thus the dim here is 256?
> And max, min is 3 dim, which defines min and max value along "points: an N ✕ 3 numpy array containing the sample points"?
> 

You are right here. 


> And how do you calculate normals?

The way we use to compute normals of a watertight mesh is the standard version. 
> May I ask did you do scale_to_unit_sphere before sampling point and calculate SDF?
> [https://github.com/marian42/mesh_to_sdf/blob/master/mesh_to_sdf/utils.py#L4](url)
> Thanks.

Regarding details about SDF, I suggest to ask the PROX team.  SDF is actually part of PROX, rather than in this work.  I have forwarded your questions to them.

**Comment by wangzheallen** [comment]
Thanks for the kind reply and forward  :-)
