### ISSUE TITLE
demo.ipynb : Contact_part difference

### ISSUE THREAD

**Issue by BupyeongHealer** [yz-cnsdqz/PSI-release#17]
Hello!
Now I'm running the demo.ipynb. But, There are still errors in code.
I have a body segments file such as gluteus and so on.
But, in code, There are butt and so on.
I mean I have no butt.json file. Is it replace with gluteus.json?

Thanks a lot!

**Comment by yz-cnsdqz** [comment]
yes. That file in PROX has been updated.

**Comment by BupyeongHealer** [comment]
@yz-cnsdqz Thank you!!
