### ISSUE TITLE
Can you kindly share the code of baseline? 

### ISSUE THREAD

**Issue by zzilch** [yz-cnsdqz/PSI-release#22]
In the paper, you mentioned that you modified the code of "Putting Humans in a Scene" and used it as a baseline.
I am also interested in the baseline, but the authors didn't release the code. I emailed them but received no reply for a long time.
Can you kindly share the code of baseline with me?

**Comment by yz-cnsdqz** [comment]
according to some agreement, I could not provide it as well unfortunately.

**Comment by zzilch** [comment]
Fine, thanks anyway.
