### ISSUE TITLE
SMPL-X Model Obtaining 

### ISSUE THREAD

**Issue by cuiyuexin** [yz-cnsdqz/PSI-release#3]
Hello!~

Nice work! Now I have a question. May I ask how can I obtain SMPL-X human mesh per-frame in PROX-E dataset? Here I mean the human recorded in the original PROX dataset but not the generated human in the network. I'm not sure whether I need to train the network in this paper or not. Maybe I should refer to https://smpl-x.is.tue.mpg.de/downloads?

Thanks a lot!

**Comment by yz-cnsdqz** [comment]
thanks for your interests! As mentioned in the paper, you could download the smplx from the link that you mentioned. Regarding the prox fitting algorithm as well as the dataset, you can check here: https://prox.is.tue.mpg.de/

**Comment by cuiyuexin** [comment]
I didn't notice that PROX dataset contains SMPL-X fitting results before your remind. Maybe I need to check the link you mentioned. Thank you very much!
