### ISSUE TITLE
Body visualization problem

### ISSUE THREAD

**Issue by cuiyuexin** [yz-cnsdqz/PSI-release#5]
Hello!~

So sorry to bother you! Now I've installed all the packages in the requirements file (except psbody-mesh and pkg-resources).  I met a problem when I run "demo.ipynb" (jupyter notebook in firefox browser). The visualization before geometry-aware fitting shows nothing but blank space but there is no bug. Is this because that I failed to install psbody-mesh package? When I installed psbody-mesh package, I followed the steps but when I run "make tests", nothing showed in my screen.

My environment: Ubuntu 16.04 + Python 3.7 + PyTorch 1.3.1 + CUDA 10.1

Thank you very much!

**Comment by yz-cnsdqz** [comment]
> Hello!~
> 
> So sorry to bother you! Now I've installed all the packages in the requirements file (except psbody-mesh and pkg-resources). I met a problem when I run "demo.ipynb" (jupyter notebook in firefox browser). The visualization before geometry-aware fitting shows nothing but blank space but there is no bug. Is this because that I failed to install psbody-mesh package? When I installed psbody-mesh package, I followed the steps but when I run "make tests", nothing showed in my screen.
> 
> My environment: Ubuntu 16.04 + Python 3.7 + PyTorch 1.3.1 + CUDA 10.1
> 
> Thank you very much!

sorry that I did not test on all web browsers. In my experience, I use google chrome and it works fine. For visualization in Jupyter notebook, I also follow the open3d instructions. You may find your solutions there.

**Comment by cuiyuexin** [comment]
Thank you for your help! I changed to chrome browser, but still blank after visualizer.show(). Maybe I should refer to open3d for help. But do you think psbody-mesh package necessary in this step?

**Comment by yz-cnsdqz** [comment]
> Thank you for your help! I changed to chrome browser, but still blank after visualizer.show(). Maybe I should refer to open3d for help. But do you think psbody-mesh package necessary in this step?

Not really. psbody-mesh is actually not used there.

**Comment by cuiyuexin** [comment]
I truly appreciate your help! Now I fixed the problem of visualization, without using JVisualizer. The JVisualizer cannot visualize all things simultaneously in my environment.

**Comment by BupyeongHealer** [comment]
@cuiyuexin I have a same issue! What did you replace with JVisualizer? I find the plotly library but not implement yet.

**Comment by BupyeongHealer** [comment]
@cuiyuexin I solved the problem replacing with plotly.
